In [1]:
import numpy as np

In [21]:
arr = np.arange(1,25,2)

In [22]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [4]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
np.random.randint(1,10,5)

array([5, 1, 5, 2, 5])

In [20]:
np.random.rand(1,3,3,5)

array([[[[0.54754864, 0.10786819, 0.55078643, 0.12259594, 0.4223331 ],
         [0.96175055, 0.30330872, 0.71695568, 0.26055237, 0.6066315 ],
         [0.92478872, 0.01421185, 0.71346897, 0.83578521, 0.40843942]],

        [[0.75174885, 0.30428008, 0.09218775, 0.15192316, 0.29738353],
         [0.17517691, 0.00627773, 0.6615833 , 0.61530638, 0.56333862],
         [0.39150808, 0.85804911, 0.72113599, 0.79757698, 0.75372068]],

        [[0.99806198, 0.10280641, 0.78068938, 0.44715382, 0.87136926],
         [0.46668909, 0.78723058, 0.66902693, 0.64924489, 0.22968422],
         [0.07912625, 0.29879503, 0.20596768, 0.29967937, 0.49609961]]]])

In [7]:
arr.max()

24

In [9]:
arr.min()

0

In [10]:
arr.argmax()

24