In [1]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[8]

8

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[0] = 9

In [8]:
arr

array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[0:5] = 9

In [12]:
arr

array([9, 9, 9, 9, 9, 5, 6, 7, 8, 9])

In [13]:
data = arr[0:5]

In [14]:
data

array([9, 9, 9, 9, 9])

In [15]:
data[:] = 99

In [16]:
data

array([99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [18]:
newData = arr.copy()

In [19]:
newData

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [21]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[0]

array([ 5, 10, 15])

In [25]:
arr_2d[0][2]

15

In [26]:
arr_2d[0,2] #hanya array dengan jumlah sedikit

15

In [28]:
arr_2d[0:2, 1:3]

array([[10, 15],
       [25, 30]])

In [29]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [30]:
arr_2d > 12

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [32]:
arr_2d[arr_2d > 17]

array([20, 25, 30, 35, 40, 45])

In [33]:
arr_2d + arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])